[package]
name = "ufo"
version = "0.1.16"
edition = "2021"

[[bin]]
name = "ufo"
path = "src/main.rs"

[dependencies]
base64 = "0.22"
crossterm = "0.28"
fancy-regex = "0.14"
getrandom = "0.3"
iana-time-zone = "0.1"
pulldown-cmark = { version = "0.12", default-features = false }
ratatui = { version = "0.29", default-features = false }
rustls-native-certs = "0.7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
similar = { version = "2", default-features = false, features = ["unicode"] }
syntect = { version = "5.3.0", default-features = false, features = ["default-fancy"] }
unicode-width = "0.2"
ureq = { version = "2.12", features = ["native-certs"] }

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[profile.release]
lto = true
strip = true
codegen-units = 1

[dev-dependencies]
vt100 = "0.15"
