import type { ReactNode } from "react";

import {
  ActionBar,
  ActionBarActions,
  ActionBarCenter,
  ActionBarTitle,
  Composer,
  IconButton,
  Prompt,
  Prompts,
  SearchField,
} from "@/blocks/action-bar";
import { Avatar, AvatarStack } from "@/blocks/avatar";
import {
  Card,
  CardAction,
  CardButton,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardImage,
  CardTitle,
} from "@/blocks/card";
import {
  ChartContainer,
  ChartLegend,
  ChartLegendContent,
  ChartStyle,
  ChartTick,
  ChartTooltip,
  ChartTooltipContent,
} from "@/blocks/chart";
import { Checkbox } from "@/blocks/checkbox";
import {
  DataTable,
  DataTableColumnHeader,
  DataTablePagination,
  DataTableSelectCell,
  DataTableSelectHeader,
  DataTableToolbar,
  DataTableViewOptions,
  useDataTable,
} from "@/blocks/data-table";
import {
  Count,
  Item,
  ItemActions,
  ItemContent,
  ItemDescription,
  ItemFooter,
  ItemGroup,
  ItemHeader,
  ItemMedia,
  ItemMeta,
  ItemSection,
  ItemSeparator,
  ItemTitle,
  StatusIcon,
  Tag,
} from "@/blocks/item";
import {
  Menu,
  MenuButton,
  MenuCheckboxItem,
  MenuContent,
  MenuItem,
  MenuLabel,
  MenuSeparator,
  MenuTrigger,
} from "@/blocks/menu";
import {
  Delta,
  ProgressStat,
  Sparkline,
  Stat,
  StatGrid,
  StatRow,
  StatRows,
  StatTile,
} from "@/blocks/stat";
import {
  AvatarPair,
  Mark,
  ScoreDot,
  Table,
  TableBody,
  TableCaption,
  TableCell,
  TableEmpty,
  TableFooter,
  TableHead,
  TableHeader,
  TableMeta,
  TableRow,
  TableSection,
  TableSkeleton,
  TableTag,
} from "@/blocks/table";
import { CodeBlock, Figure, Prose } from "@/blocks/typography";

import "@/blocks/tokens.css";

/** The element every other block needs above it: it carries the type scale, the control resets and
 *  the surface colour the blocks draw against, none of which a block sets on itself. Wrap the page
 *  body in one and compose inside it. */
export function BlockRoot({ children }: { children: ReactNode }) {
  return <div className="blk-root">{children}</div>;
}

export {
  ActionBar,
  ActionBarActions,
  ActionBarCenter,
  ActionBarTitle,
  Avatar,
  AvatarPair,
  AvatarStack,
  Card,
  CardAction,
  CardButton,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardImage,
  CardTitle,
  ChartContainer,
  ChartLegend,
  ChartLegendContent,
  ChartStyle,
  ChartTick,
  ChartTooltip,
  ChartTooltipContent,
  Checkbox,
  CodeBlock,
  Composer,
  Count,
  DataTable,
  DataTableColumnHeader,
  DataTablePagination,
  DataTableSelectCell,
  DataTableSelectHeader,
  DataTableToolbar,
  DataTableViewOptions,
  Delta,
  Figure,
  IconButton,
  Item,
  ItemActions,
  ItemContent,
  ItemDescription,
  ItemFooter,
  ItemGroup,
  ItemHeader,
  ItemMedia,
  ItemMeta,
  ItemSection,
  ItemSeparator,
  ItemTitle,
  Mark,
  Menu,
  MenuButton,
  MenuCheckboxItem,
  MenuContent,
  MenuItem,
  MenuLabel,
  MenuSeparator,
  MenuTrigger,
  ProgressStat,
  Prompt,
  Prompts,
  Prose,
  ScoreDot,
  SearchField,
  Sparkline,
  Stat,
  StatGrid,
  StatRow,
  StatRows,
  StatTile,
  StatusIcon,
  Table,
  TableBody,
  TableCaption,
  TableCell,
  TableEmpty,
  TableFooter,
  TableHead,
  TableHeader,
  TableMeta,
  TableRow,
  TableSection,
  TableSkeleton,
  TableTag,
  Tag,
  useDataTable,
};
