// Generated by `uv run python -m ufo_testsupport.contract` from core's pydantic models. Do not edit.

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ActivityEvent {
    pub kind: String,
    pub text: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AskQuestion {
    pub question: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub options: Option<Vec<QuestionOption>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub multi_select: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub free_text_only: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub header: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub allow_attachments: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub chosen: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AskUserInput {
    pub title: String,
    pub questions: Vec<AskQuestion>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub icon: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ConnectRequest {
    pub provider: String,
    pub requester_member_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub shared: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub grantee_agent_id: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CredentialPrompt {
    pub slot: String,
    pub prompt: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CredentialRequest {
    pub reason: String,
    pub prompts: Vec<CredentialPrompt>,
    pub sealed: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Meter {
    pub tokens: i64,
    pub cost_micro_usd: i64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ObjectRef {
    pub kind: String,
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub agent: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct QuestionOption {
    pub label: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SourceRef {
    pub kind: String,
    pub title: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub r#ref: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub provider: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SubagentRun {
    pub profile: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    pub conversation_id: String,
    pub events: Vec<ActivityEvent>,
    pub output: String,
    pub subagents: Vec<SubagentRun>,
    pub running: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub turn_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parent_turn_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub current: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct TerminalFrame {
    pub status: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub text: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub incomplete_reason: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error_class: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error_message: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tokens: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cost_micro_usd: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cache_percent: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reasoning: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub environment: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub question: Option<AskUserInput>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub credential_request: Option<CredentialRequest>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub connect_request: Option<ConnectRequest>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub created: Option<Vec<ObjectRef>>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct TurnRecord {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    pub steps: Vec<Step>,
    pub runs: Vec<SubagentRun>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub meter: Option<Meter>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub end: Option<TurnEnd>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "kind")]
#[rustfmt::skip]
#[allow(clippy::large_enum_variant)]
pub enum Step {
    #[serde(rename = "text")]
    Text {
        text: String,
        open: bool,
    },
    #[serde(rename = "tool")]
    Tool {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        label: Option<String>,
        call_id: String,
        sources: Vec<SourceRef>,
        open: bool,
    },
    #[serde(rename = "reply")]
    Reply {
        id: String,
        text: String,
    },
    #[serde(rename = "comment")]
    Comment {
        id: String,
        text: String,
    },
    #[serde(rename = "drain")]
    Drain {
        arrivals: Vec<String>,
    },
    #[serde(rename = "resumed")]
    Resumed {
        attempt: String,
    },
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "kind")]
#[rustfmt::skip]
#[allow(clippy::large_enum_variant)]
pub enum TurnEnd {
    #[serde(rename = "terminal")]
    Terminal {
        frame: TerminalFrame,
        at: String,
    },
    #[serde(rename = "parked")]
    Parked {
        message: String,
    },
    #[serde(rename = "lost")]
    Lost,
}
