"""The turn record contract, rendered from core's pydantic models for the frontends that hold it.

`TurnRecord` and every model it reaches are rendered as one TypeScript module the portal imports
its record types from, and a fixture holding an instance of every variant is written beside the
portal's tests, where the record suite folds and lays it out. Both files are checked in, and
`test_contract.py` fails when either stops matching the models. Regenerate:
`uv run python -m ufo_testsupport.contract`."""

import json
from datetime import UTC, datetime
from pathlib import Path
from typing import Any
from uuid import UUID

from pydantic import TypeAdapter
from pydantic.json_schema import GenerateJsonSchema, JsonSchemaMode
from ufo_ext_memory.workspace_export import ExportView
from ufo_ext_web.surface import _sse

from ufo.harness.models.interface import TextDelta
from ufo.runtime.hub import (
    Absorbed,
    Activity,
    CostTick,
    LiveFrame,
    Parked,
    Reply,
    Resumed,
    SourceRef,
    Sources,
    SubagentActivity,
    Terminal,
)
from ufo.runtime.turns.record import (
    ActivityEvent,
    CommentStep,
    DrainStep,
    Meter,
    ReplyStep,
    ResumedStep,
    Step,
    SubagentRun,
    TerminalEnd,
    TextStep,
    ToolStep,
    TurnEnd,
    TurnRecord,
    fold,
)
from ufo.schema.records import AskQuestion, AskUserInput, QuestionOption, TerminalFrame
from ufo_testsupport.sse_fixture import _row

FRONTEND = Path(__file__).parents[2] / "extensions" / "web" / "frontend"
CONTRACT_PATH = FRONTEND / "src" / "lib" / "contract.ts"
RUST_CONTRACT_PATH = Path(__file__).parents[2] / "client" / "src" / "record.rs"
RUST_HEADER = (
    "// Generated by `uv run python -m ufo_testsupport.contract` from core's pydantic models."
    " Do not edit."
)
RUST_SCALARS = {"string": "String", "integer": "i64", "number": "f64", "boolean": "bool"}
RUST_KEYWORDS = frozenset({"ref", "type", "match", "self", "use", "mod", "loop", "move", "as"})
RECORD_FIXTURE_PATH = FRONTEND / "tests" / "fixtures" / "record.json"
FOLD_FIXTURE_PATH = FRONTEND / "tests" / "fixtures" / "fold.json"
HEADER = (
    "// Generated by `uv run python -m ufo_testsupport.contract` from core's pydantic models."
    " Do not edit."
)
ROOT = TurnRecord
ALIASES: dict[str, Any] = {"Step": Step, "TurnEnd": TurnEnd}
MODE: JsonSchemaMode = "serialization"
SCALARS = {"string": "string", "integer": "number", "number": "number", "boolean": "boolean"}

TURN_ID = UUID("33333333-3333-4333-8333-333333333333")
ARRIVAL_ID = UUID("88888888-8888-4888-8888-888888888888")
REPLY_ID = UUID("66666666-6666-4666-8666-666666666666")
RUN_ID = UUID("99999999-9999-4999-8999-999999999999")
RUN_CONVERSATION_ID = UUID("77777777-7777-4777-8777-777777777777")
CHILD_RUN_ID = UUID("aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa")
CHILD_CONVERSATION_ID = UUID("bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb")
COMMENT_ID = UUID("cccccccc-cccc-4ccc-8ccc-cccccccccccc")
ATTEMPT = "44444444444444444444444444444444"
ENDED_AT = datetime(2026, 9, 15, 12, 0, tzinfo=UTC)


class _Definitions(GenerateJsonSchema):
    """Every model under one `$defs`, the root included, so one walk renders them all."""

    def generate(self, schema: Any, mode: JsonSchemaMode = MODE) -> dict[str, Any]:
        rendered = super().generate(schema, mode=mode)
        title = rendered.pop("title")
        defs = rendered.pop("$defs", {})
        defs[title] = rendered
        return {"$defs": defs}


def _reference(schema: dict[str, Any]) -> str | None:
    ref = schema.get("$ref")
    return None if ref is None else ref.rsplit("/", 1)[-1]


def _union_name(members: list[dict[str, Any]], aliases: dict[frozenset[str], str]) -> str | None:
    refs = [_reference(member) for member in members]
    if any(ref is None for ref in refs):
        return None
    return aliases.get(frozenset(ref for ref in refs if ref is not None))


def _render_type(schema: dict[str, Any], aliases: dict[frozenset[str], str]) -> str:
    named = _reference(schema)
    if named is not None:
        return named
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    members = schema.get("anyOf") or schema.get("oneOf")
    if members is not None:
        return _union_name(members, aliases) or " | ".join(
            _render_type(member, aliases) for member in members
        )
    kind = schema.get("type")
    if kind in SCALARS:
        return SCALARS[kind]
    if kind == "null":
        return "null"
    if kind == "array":
        item = _render_type(schema["items"], aliases)
        return (f"({item})" if " | " in item else item) + "[]"
    if kind == "object":
        extra = schema.get("additionalProperties")
        value = _render_type(extra, aliases) if isinstance(extra, dict) else "unknown"
        return f"Record<string, {value}>"
    return "unknown"


def _render_model(name: str, schema: dict[str, Any], aliases: dict[frozenset[str], str]) -> str:
    """A field with a default is optional, except a discriminator: its one value is always
    serialized, and a union narrows on it only when it is required."""
    required = set(schema.get("required", ()))
    lines = [f"export type {name} = {{"]
    for field, held in schema.get("properties", {}).items():
        mark = "" if field in required or "const" in held else "?"
        lines.append(f"  {field}{mark}: {_render_type(held, aliases)};")
    lines.append("};")
    return "\n".join(lines)


def rendered_contract() -> str:
    """The TypeScript module: one type per model `TurnRecord` reaches, and one alias per union
    the record names."""
    defs = TypeAdapter(ROOT).json_schema(schema_generator=_Definitions, mode=MODE)["$defs"]
    defs.update(
        TypeAdapter(ExportView).json_schema(schema_generator=_Definitions, mode=MODE)["$defs"]
    )
    aliases: dict[frozenset[str], str] = {}
    for name, union in ALIASES.items():
        members = TypeAdapter(union).json_schema(mode=MODE)["oneOf"]
        aliases[frozenset(ref for ref in (_reference(m) for m in members) if ref)] = name
    parts = [HEADER]
    parts.extend(_render_model(name, defs[name], aliases) for name in sorted(defs))
    parts.extend(
        f"export type {name} = {' | '.join(sorted(members))};"
        for members, name in sorted(aliases.items(), key=lambda held: held[1])
    )
    return "\n\n".join(parts) + "\n"


def _rust_type(schema: dict[str, Any], aliases: dict[frozenset[str], str]) -> str:
    """The Rust type a schema renders to. A string literal set is a `String` here — the tagged
    enums the unions need are the one place Rust reads a literal — and a nullable type an
    `Option`."""
    named = _reference(schema)
    if named is not None:
        return named
    if "const" in schema or "enum" in schema:
        return "String"
    members = schema.get("anyOf") or schema.get("oneOf")
    if members is not None:
        alias = _union_name(members, aliases)
        if alias is not None:
            return alias
        held = [member for member in members if member.get("type") != "null"]
        inner = _rust_type(held[0], aliases) if len(held) == 1 else "serde_json::Value"
        return f"Option<{inner}>" if len(held) < len(members) else inner
    kind = schema.get("type")
    if kind in RUST_SCALARS:
        return RUST_SCALARS[kind]
    if kind == "array":
        return f"Vec<{_rust_type(schema['items'], aliases)}>"
    return "serde_json::Value"


def _rust_field(name: str, schema: dict[str, Any], required: bool, aliases: Any) -> list[str]:
    rendered = _rust_type(schema, aliases)
    optional = not required and not rendered.startswith("Option<")
    if optional:
        rendered = f"Option<{rendered}>"
    lines: list[str] = []
    if rendered.startswith("Option<"):
        lines.append('    #[serde(default, skip_serializing_if = "Option::is_none")]')
    ident = f"r#{name}" if name in RUST_KEYWORDS else name
    lines.append(f"    pub {ident}: {rendered},")
    return lines


def _rust_struct(name: str, schema: dict[str, Any], aliases: dict[frozenset[str], str]) -> str:
    required = set(schema.get("required", ()))
    lines = ["#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]", f"pub struct {name} {{"]
    for field, held in schema.get("properties", {}).items():
        lines.extend(_rust_field(field, held, field in required, aliases))
    lines.append("}")
    return "\n".join(lines)


def _rust_enum(
    name: str, members: list[str], defs: dict[str, Any], aliases: dict[frozenset[str], str]
) -> str:
    """A discriminated union as a tagged enum: each member's fields ride the variant, and the
    discriminator is the tag serde reads, so the member structs are not emitted on their own.
    rustfmt folds a short variant onto one line, so the enum is skipped and stays as rendered; the
    variants take the contract's shape, so their size spread is not clippy's to judge."""
    lines = [
        "#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]",
        '#[serde(tag = "kind")]',
        "#[rustfmt::skip]",
        "#[allow(clippy::large_enum_variant)]",
        f"pub enum {name} {{",
    ]
    for member in members:
        schema = defs[member]
        tag = schema["properties"]["kind"]["const"]
        variant = "".join(part.capitalize() for part in tag.split("_"))
        lines.append(f'    #[serde(rename = "{tag}")]')
        fields = [(field, held) for field, held in schema["properties"].items() if field != "kind"]
        if not fields:
            lines.append(f"    {variant},")
            continue
        lines.append(f"    {variant} {{")
        required = set(schema.get("required", ()))
        for field, held in fields:
            lines.extend(
                "    " + line.replace("    pub ", "    ", 1)
                for line in _rust_field(field, held, field in required, aliases)
            )
        lines.append("    },")
    lines.append("}")
    return "\n".join(lines)


def rendered_rust() -> str:
    """The Rust module the terminal client folds into: one struct per model the record reaches,
    one tagged enum per union it names."""
    defs = TypeAdapter(ROOT).json_schema(schema_generator=_Definitions, mode=MODE)["$defs"]
    aliases: dict[frozenset[str], str] = {}
    unions: dict[str, list[str]] = {}
    for name, union in ALIASES.items():
        members = TypeAdapter(union).json_schema(mode=MODE)["oneOf"]
        refs = [ref for ref in (_reference(m) for m in members) if ref]
        aliases[frozenset(refs)] = name
        unions[name] = refs
    variants = {member for members in unions.values() for member in members}
    parts = [RUST_HEADER, "use serde::{Deserialize, Serialize};"]
    parts.extend(
        _rust_struct(name, defs[name], aliases) for name in sorted(defs) if name not in variants
    )
    parts.extend(_rust_enum(name, unions[name], defs, aliases) for name in sorted(unions))
    return "\n\n".join(parts) + "\n"


def record_fixture() -> TurnRecord:
    """A record holding every step kind, a nested run, and a done terminal that asked a question."""
    page = SourceRef(kind="web", title="Docs", url="https://docs.example/a")
    return TurnRecord(
        id=TURN_ID,
        steps=(
            TextStep(text="Reading the changelog first.", open=False),
            ToolStep(label="Reading the changelog.", call_id="c1", sources=(page,), open=False),
            ReplyStep(id=REPLY_ID, text="Filed the launch issue as metalcraftai/ufo#1801."),
            CommentStep(id=ARRIVAL_ID, text="A comment landed on Slack."),
            DrainStep(arrivals=(ARRIVAL_ID,)),
            ResumedStep(attempt="44444444444444444444444444444444"),
            ToolStep(label=None, call_id="", sources=(page,), open=False),
            TextStep(text="It shipped Tuesday.", open=False),
        ),
        runs=(
            SubagentRun(
                profile="deep_research",
                name="Calendar check",
                conversation_id=RUN_CONVERSATION_ID,
                events=(ActivityEvent(kind="activity", text="Reading the calendar."),),
                output="found it",
                subagents=(
                    SubagentRun(
                        profile="general_purpose",
                        conversation_id=RUN_CONVERSATION_ID,
                        events=(),
                        output="",
                        subagents=(),
                        running=True,
                        turn_id=RUN_ID,
                        parent_turn_id=TURN_ID,
                        current="Looking up info",
                    ),
                ),
                running=False,
            ),
        ),
        meter=Meter(tokens=12, cost_micro_usd=110),
        end=TerminalEnd(
            frame=TerminalFrame(
                status="done",
                text="It shipped Tuesday.",
                tokens=12,
                cost_micro_usd=110,
                cache_percent=40,
                model="claude-opus-4-8",
                question=AskUserInput(
                    title="One question",
                    questions=(
                        AskQuestion(
                            question="Which calendar?",
                            options=(QuestionOption(label="Work"), QuestionOption(label="Home")),
                        ),
                    ),
                ),
            ),
            at=ENDED_AT,
        ),
    )


def rendered_record() -> str:
    return json.dumps(record_fixture().model_dump(mode="json"), indent=2, ensure_ascii=False) + "\n"


def conformance_cases() -> list[tuple[str, tuple[LiveFrame, ...]]]:
    """Frame sequences every fold must fold alike: the words, steps, drains, replies, resumes, runs
    and ends a turn can put on its stream, in the orders that decide a record's shape."""
    page = SourceRef(kind="web", title="Docs", url="https://docs.example/a")
    plan = SourceRef(kind="workspace", title="Plan", ref="page/1", provider="notion")
    done = Terminal(
        frame=TerminalFrame(
            status="done",
            text="It shipped Tuesday.",
            tokens=12,
            cost_micro_usd=110,
            model="claude-opus-4-8",
        )
    )
    run = SubagentActivity(
        turn_id=RUN_ID,
        parent_turn_id=TURN_ID,
        conversation_id=RUN_CONVERSATION_ID,
        profile="deep_research",
        name="Calendar check",
    )
    child = SubagentActivity(
        turn_id=CHILD_RUN_ID,
        parent_turn_id=RUN_ID,
        conversation_id=CHILD_CONVERSATION_ID,
        profile="general_purpose",
    )
    return [
        (
            "words between two tool steps, then the answer",
            (
                TextDelta(text="Reading the changelog first."),
                Activity(text="Reading the changelog.", call_id="c1"),
                TextDelta(text="Checking the tags now."),
                Activity(text="Checking the release tags.", call_id="c2"),
                TextDelta(text="It shipped "),
                TextDelta(text="Tuesday."),
                done,
            ),
        ),
        (
            "sources before any label open an unlabelled step, and words close it",
            (
                Sources(items=(page,)),
                Sources(items=(page, plan)),
                TextDelta(text="Here."),
                Activity(text="Listing."),
                Sources(items=(plan,)),
                done,
            ),
        ),
        (
            "a drain cuts the round, a replayed reply states itself once, a comment is kept",
            (
                Reply(id=REPLY_ID, message_ref=ARRIVAL_ID, text="Filed it."),
                Reply(id=REPLY_ID, message_ref=ARRIVAL_ID, text="Filed it."),
                Absorbed(arrivals=(ARRIVAL_ID,)),
                Absorbed(arrivals=(ARRIVAL_ID,)),
                TextDelta(text="2"),
                CostTick(cost_micro_usd=110, tokens=12),
                Reply(id=COMMENT_ID, text="A comment landed on Slack.", is_comment=True),
                Terminal(frame=TerminalFrame(status="done", text="2", model="claude-opus-4-8")),
            ),
        ),
        (
            "a resume between words, then a park",
            (
                TextDelta(text="Half"),
                Resumed(attempt=ATTEMPT),
                TextDelta(text="way"),
                Parked(message="Spend cap reached; the turn resumes when the cap is raised."),
            ),
        ),
        (
            "a run nests its child under it and both end",
            (
                run,
                run.model_copy(update={"activity": "Reading the calendar."}),
                child,
                child.model_copy(update={"activity": "Looking up info"}),
                child.model_copy(update={"status": "done"}),
                run.model_copy(update={"status": "done"}),
                done,
            ),
        ),
    ]


def rendered_fold() -> str:
    """Each case as the stream would deliver it — the web surface's own SSE rows — beside the record
    the reference fold reaches, with no null field, so a fold in any language replays the rows and
    compares its record after dropping its own nulls."""
    cases = []
    for name, frames in conformance_cases():
        record = TurnRecord(id=TURN_ID, steps=(), runs=(), meter=None, end=None)
        for frame in frames:
            record = fold(record, frame, ENDED_AT)
        cases.append(
            {
                "name": name,
                "frames": [_row(_sse("", frame)) for frame in frames],
                "record": record.model_dump(mode="json", exclude_none=True),
            }
        )
    return json.dumps(cases, indent=2, ensure_ascii=False) + "\n"


def write_contract() -> None:
    CONTRACT_PATH.write_text(rendered_contract())
    RUST_CONTRACT_PATH.write_text(rendered_rust())
    RECORD_FIXTURE_PATH.parent.mkdir(parents=True, exist_ok=True)
    RECORD_FIXTURE_PATH.write_text(rendered_record())
    FOLD_FIXTURE_PATH.write_text(rendered_fold())


if __name__ == "__main__":
    write_contract()
    for written in (CONTRACT_PATH, RUST_CONTRACT_PATH, RECORD_FIXTURE_PATH, FOLD_FIXTURE_PATH):
        print(f"wrote {written}")
