"""The turn record contract, rendered from core's pydantic models for the frontends that hold it.

`TurnRecord` and every model it reaches are rendered as one TypeScript module the portal imports
its record types from, and a fixture holding an instance of every variant is written beside the
portal's tests, where the record suite folds and lays it out. Both files are checked in, and
`test_contract.py` fails when either stops matching the models. Regenerate:
`uv run python -m ufo_testsupport.contract`."""

import json
from datetime import UTC, datetime
from pathlib import Path
from typing import Any
from uuid import UUID

from pydantic import TypeAdapter
from pydantic.json_schema import GenerateJsonSchema, JsonSchemaMode

from ufo.runtime.hub import SourceRef
from ufo.runtime.turns.record import (
    ActivityEvent,
    CommentStep,
    DrainStep,
    Meter,
    ReplyStep,
    ResumedStep,
    Step,
    SubagentRun,
    TerminalEnd,
    TextStep,
    ToolStep,
    TurnEnd,
    TurnRecord,
)
from ufo.schema.records import AskQuestion, AskUserInput, QuestionOption, TerminalFrame

FRONTEND = Path(__file__).parents[2] / "extensions" / "web" / "frontend"
CONTRACT_PATH = FRONTEND / "src" / "lib" / "contract.ts"
RECORD_FIXTURE_PATH = FRONTEND / "tests" / "fixtures" / "record.json"
HEADER = (
    "// Generated by `uv run python -m ufo_testsupport.contract` from core's pydantic models."
    " Do not edit."
)
ROOT = TurnRecord
ALIASES: dict[str, Any] = {"Step": Step, "TurnEnd": TurnEnd}
MODE: JsonSchemaMode = "serialization"
SCALARS = {"string": "string", "integer": "number", "number": "number", "boolean": "boolean"}

TURN_ID = UUID("33333333-3333-4333-8333-333333333333")
ARRIVAL_ID = UUID("88888888-8888-4888-8888-888888888888")
REPLY_ID = UUID("66666666-6666-4666-8666-666666666666")
RUN_ID = UUID("99999999-9999-4999-8999-999999999999")
RUN_CONVERSATION_ID = UUID("77777777-7777-4777-8777-777777777777")
ENDED_AT = datetime(2026, 9, 15, 12, 0, tzinfo=UTC)


class _Definitions(GenerateJsonSchema):
    """Every model under one `$defs`, the root included, so one walk renders them all."""

    def generate(self, schema: Any, mode: JsonSchemaMode = MODE) -> dict[str, Any]:
        rendered = super().generate(schema, mode=mode)
        title = rendered.pop("title")
        defs = rendered.pop("$defs", {})
        defs[title] = rendered
        return {"$defs": defs}


def _reference(schema: dict[str, Any]) -> str | None:
    ref = schema.get("$ref")
    return None if ref is None else ref.rsplit("/", 1)[-1]


def _union_name(members: list[dict[str, Any]], aliases: dict[frozenset[str], str]) -> str | None:
    refs = [_reference(member) for member in members]
    if any(ref is None for ref in refs):
        return None
    return aliases.get(frozenset(ref for ref in refs if ref is not None))


def _render_type(schema: dict[str, Any], aliases: dict[frozenset[str], str]) -> str:
    named = _reference(schema)
    if named is not None:
        return named
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    members = schema.get("anyOf") or schema.get("oneOf")
    if members is not None:
        return _union_name(members, aliases) or " | ".join(
            _render_type(member, aliases) for member in members
        )
    kind = schema.get("type")
    if kind in SCALARS:
        return SCALARS[kind]
    if kind == "null":
        return "null"
    if kind == "array":
        item = _render_type(schema["items"], aliases)
        return (f"({item})" if " | " in item else item) + "[]"
    if kind == "object":
        extra = schema.get("additionalProperties")
        value = _render_type(extra, aliases) if isinstance(extra, dict) else "unknown"
        return f"Record<string, {value}>"
    return "unknown"


def _render_model(name: str, schema: dict[str, Any], aliases: dict[frozenset[str], str]) -> str:
    """A field with a default is optional, except a discriminator: its one value is always
    serialized, and a union narrows on it only when it is required."""
    required = set(schema.get("required", ()))
    lines = [f"export type {name} = {{"]
    for field, held in schema.get("properties", {}).items():
        mark = "" if field in required or "const" in held else "?"
        lines.append(f"  {field}{mark}: {_render_type(held, aliases)};")
    lines.append("};")
    return "\n".join(lines)


def rendered_contract() -> str:
    """The TypeScript module: one type per model `TurnRecord` reaches, and one alias per union
    the record names."""
    defs = TypeAdapter(ROOT).json_schema(schema_generator=_Definitions, mode=MODE)["$defs"]
    aliases: dict[frozenset[str], str] = {}
    for name, union in ALIASES.items():
        members = TypeAdapter(union).json_schema(mode=MODE)["oneOf"]
        aliases[frozenset(ref for ref in (_reference(m) for m in members) if ref)] = name
    parts = [HEADER]
    parts.extend(_render_model(name, defs[name], aliases) for name in sorted(defs))
    parts.extend(
        f"export type {name} = {' | '.join(sorted(members))};"
        for members, name in sorted(aliases.items(), key=lambda held: held[1])
    )
    return "\n\n".join(parts) + "\n"


def record_fixture() -> TurnRecord:
    """A record holding every step kind, a nested run, and a done terminal that asked a question."""
    page = SourceRef(kind="web", title="Docs", url="https://docs.example/a")
    return TurnRecord(
        id=TURN_ID,
        steps=(
            TextStep(text="Reading the changelog first.", open=False),
            ToolStep(label="Reading the changelog.", sources=(page,), open=False),
            ReplyStep(id=REPLY_ID, text="Filed the launch issue as metalcraftai/ufo#1801."),
            CommentStep(id=ARRIVAL_ID, text="A comment landed on Slack."),
            DrainStep(arrivals=(ARRIVAL_ID,)),
            ResumedStep(attempt="44444444444444444444444444444444"),
            ToolStep(label=None, sources=(page,), open=False),
            TextStep(text="It shipped Tuesday.", open=False),
        ),
        runs=(
            SubagentRun(
                profile="deep_research",
                name="Calendar check",
                conversation_id=RUN_CONVERSATION_ID,
                events=(ActivityEvent(kind="activity", text="Reading the calendar."),),
                output="found it",
                subagents=(
                    SubagentRun(
                        profile="general_purpose",
                        conversation_id=RUN_CONVERSATION_ID,
                        events=(),
                        output="",
                        subagents=(),
                        running=True,
                        turn_id=RUN_ID,
                        parent_turn_id=TURN_ID,
                        current="Looking up info",
                    ),
                ),
                running=False,
            ),
        ),
        meter=Meter(tokens=12, cost_micro_usd=110),
        end=TerminalEnd(
            frame=TerminalFrame(
                status="done",
                text="It shipped Tuesday.",
                tokens=12,
                cost_micro_usd=110,
                cache_percent=40,
                model="claude-opus-4-8",
                question=AskUserInput(
                    title="One question",
                    questions=(
                        AskQuestion(
                            question="Which calendar?",
                            options=(QuestionOption(label="Work"), QuestionOption(label="Home")),
                        ),
                    ),
                ),
            ),
            at=ENDED_AT,
        ),
    )


def rendered_record() -> str:
    return json.dumps(record_fixture().model_dump(mode="json"), indent=2, ensure_ascii=False) + "\n"


def write_contract() -> None:
    CONTRACT_PATH.write_text(rendered_contract())
    RECORD_FIXTURE_PATH.parent.mkdir(parents=True, exist_ok=True)
    RECORD_FIXTURE_PATH.write_text(rendered_record())


if __name__ == "__main__":
    write_contract()
    print(f"wrote {CONTRACT_PATH}\nwrote {RECORD_FIXTURE_PATH}")
