# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: photon/imessage/v1/address_types.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'photon/imessage/v1/address_types.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&photon/imessage/v1/address_types.proto\x12\x12photon.imessage.v1\"\x83\x01\n\x18SingleServiceAddressInfo\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x34\n\x07service\x18\x02 \x01(\x0e\x32#.photon.imessage.v1.ChatServiceType\x12\x14\n\x07\x63ountry\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\n\n\x08_country\"\x83\x01\n\x17MultiServiceAddressInfo\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x35\n\x08services\x18\x02 \x03(\x0e\x32#.photon.imessage.v1.ChatServiceType\x12\x14\n\x07\x63ountry\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\n\n\x08_country*\x8a\x01\n\x0f\x43hatServiceType\x12!\n\x1d\x43HAT_SERVICE_TYPE_UNSPECIFIED\x10\x00\x12\x1e\n\x1a\x43HAT_SERVICE_TYPE_IMESSAGE\x10\x01\x12\x19\n\x15\x43HAT_SERVICE_TYPE_SMS\x10\x02\x12\x19\n\x15\x43HAT_SERVICE_TYPE_RCS\x10\x03\x42\t\xba\x02\x06PIMsg_b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'photon.imessage.v1.address_types_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\272\002\006PIMsg_'
  _globals['_CHATSERVICETYPE']._serialized_start=331
  _globals['_CHATSERVICETYPE']._serialized_end=469
  _globals['_SINGLESERVICEADDRESSINFO']._serialized_start=63
  _globals['_SINGLESERVICEADDRESSINFO']._serialized_end=194
  _globals['_MULTISERVICEADDRESSINFO']._serialized_start=197
  _globals['_MULTISERVICEADDRESSINFO']._serialized_end=328
# @@protoc_insertion_point(module_scope)
