# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: photon/imessage/v1/attachment_types.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'photon/imessage/v1/attachment_types.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)photon/imessage/v1/attachment_types.proto\x12\x12photon.imessage.v1\"\xde\x02\n\x0e\x41ttachmentInfo\x12\x0c\n\x04guid\x18\x01 \x01(\t\x12\x1a\n\roriginal_guid\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x11\n\tfile_name\x18\x03 \x01(\t\x12\x11\n\tmime_type\x18\x04 \x01(\t\x12\x0b\n\x03uti\x18\x05 \x01(\t\x12\x13\n\x0btotal_bytes\x18\x06 \x01(\x03\x12\x13\n\x0bis_outgoing\x18\x07 \x01(\x08\x12\x39\n\x0etransfer_state\x18\x08 \x01(\x0e\x32!.photon.imessage.v1.TransferState\x12\x11\n\tis_hidden\x18\t \x01(\x08\x12\x12\n\nis_sticker\x18\n \x01(\x08\x12>\n\x0e\x63ompanion_kind\x18\x0b \x01(\x0e\x32!.photon.imessage.v1.CompanionKindH\x01\x88\x01\x01\x42\x10\n\x0e_original_guidB\x11\n\x0f_companion_kind\"{\n\rCompanionInfo\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x11\n\tmime_type\x18\x02 \x01(\t\x12\x13\n\x0btotal_bytes\x18\x03 \x01(\x03\x12/\n\x04kind\x18\x04 \x01(\x0e\x32!.photon.imessage.v1.CompanionKind\"J\n\tCompanion\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12/\n\x04kind\x18\x02 \x01(\x0e\x32!.photon.imessage.v1.CompanionKind*\xc9\x01\n\rTransferState\x12\x1a\n\x16TRANSFER_STATE_PENDING\x10\x00\x12\'\n\x1aTRANSFER_STATE_UNAVAILABLE\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\x1f\n\x1bTRANSFER_STATE_TRANSFERRING\x10\x01\x12\x19\n\x15TRANSFER_STATE_FAILED\x10\x02\x12\x1b\n\x17TRANSFER_STATE_FINISHED\x10\x05\x12\x1a\n\x16TRANSFER_STATE_UNKNOWN\x10\x06*T\n\rCompanionKind\x12\x1e\n\x1a\x43OMPANION_KIND_UNSPECIFIED\x10\x00\x12#\n\x1f\x43OMPANION_KIND_LIVE_PHOTO_VIDEO\x10\x01\x42\t\xba\x02\x06PIMsg_b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'photon.imessage.v1.attachment_types_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\272\002\006PIMsg_'
  _globals['_TRANSFERSTATE']._serialized_start=620
  _globals['_TRANSFERSTATE']._serialized_end=821
  _globals['_COMPANIONKIND']._serialized_start=823
  _globals['_COMPANIONKIND']._serialized_end=907
  _globals['_ATTACHMENTINFO']._serialized_start=66
  _globals['_ATTACHMENTINFO']._serialized_end=416
  _globals['_COMPANIONINFO']._serialized_start=418
  _globals['_COMPANIONINFO']._serialized_end=541
  _globals['_COMPANION']._serialized_start=543
  _globals['_COMPANION']._serialized_end=617
# @@protoc_insertion_point(module_scope)
