# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from ufo_ext_imessage.proto.photon.imessage.v1 import chat_service_pb2 as photon_dot_imessage_dot_v1_dot_chat__service__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in photon/imessage/v1/chat_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ChatServiceStub(object):
    """---------------------------------------------------------------------------
    Service
    ---------------------------------------------------------------------------

    Chat-level reads, mutations, and event streams.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateChat = channel.unary_unary(
                '/photon.imessage.v1.ChatService/CreateChat',
                request_serializer=photon_dot_imessage_dot_v1_dot_chat__service__pb2.CreateChatRequest.SerializeToString,
                response_deserializer=photon_dot_imessage_dot_v1_dot_chat__service__pb2.CreateChatResponse.FromString,
                _registered_method=True)
        self.MarkChatRead = channel.unary_unary(
                '/photon.imessage.v1.ChatService/MarkChatRead',
                request_serializer=photon_dot_imessage_dot_v1_dot_chat__service__pb2.MarkChatReadRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.SetBackground = channel.unary_unary(
                '/photon.imessage.v1.ChatService/SetBackground',
                request_serializer=photon_dot_imessage_dot_v1_dot_chat__service__pb2.SetBackgroundRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.RemoveBackground = channel.unary_unary(
                '/photon.imessage.v1.ChatService/RemoveBackground',
                request_serializer=photon_dot_imessage_dot_v1_dot_chat__service__pb2.RemoveBackgroundRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ShareContactInfo = channel.unary_unary(
                '/photon.imessage.v1.ChatService/ShareContactInfo',
                request_serializer=photon_dot_imessage_dot_v1_dot_chat__service__pb2.ShareContactInfoRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.SetTyping = channel.unary_unary(
                '/photon.imessage.v1.ChatService/SetTyping',
                request_serializer=photon_dot_imessage_dot_v1_dot_chat__service__pb2.SetTypingRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetChat = channel.unary_unary(
                '/photon.imessage.v1.ChatService/GetChat',
                request_serializer=photon_dot_imessage_dot_v1_dot_chat__service__pb2.GetChatRequest.SerializeToString,
                response_deserializer=photon_dot_imessage_dot_v1_dot_chat__service__pb2.GetChatResponse.FromString,
                _registered_method=True)
        self.GetChatCount = channel.unary_unary(
                '/photon.imessage.v1.ChatService/GetChatCount',
                request_serializer=photon_dot_imessage_dot_v1_dot_chat__service__pb2.GetChatCountRequest.SerializeToString,
                response_deserializer=photon_dot_imessage_dot_v1_dot_chat__service__pb2.GetChatCountResponse.FromString,
                _registered_method=True)
        self.HasBackground = channel.unary_unary(
                '/photon.imessage.v1.ChatService/HasBackground',
                request_serializer=photon_dot_imessage_dot_v1_dot_chat__service__pb2.HasBackgroundRequest.SerializeToString,
                response_deserializer=photon_dot_imessage_dot_v1_dot_chat__service__pb2.HasBackgroundResponse.FromString,
                _registered_method=True)
        self.SubscribeChatEvents = channel.unary_stream(
                '/photon.imessage.v1.ChatService/SubscribeChatEvents',
                request_serializer=photon_dot_imessage_dot_v1_dot_chat__service__pb2.SubscribeChatEventsRequest.SerializeToString,
                response_deserializer=photon_dot_imessage_dot_v1_dot_chat__service__pb2.SubscribeChatEventsResponse.FromString,
                _registered_method=True)


class ChatServiceServicer(object):
    """---------------------------------------------------------------------------
    Service
    ---------------------------------------------------------------------------

    Chat-level reads, mutations, and event streams.
    """

    def CreateChat(self, request, context):
        """Writes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MarkChatRead(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetBackground(self, request, context):
        """Over HTTP, `data` rides base64-encoded in the JSON body (proto3-JSON
        `bytes` representation).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveBackground(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShareContactInfo(self, request, context):
        """Pushes the local user's name-and-photo card into the target chat so
        the recipient sees it in their contact suggestions. No observable
        local state change.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTyping(self, request, context):
        """Transient typing-indicator write. No persisted state.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChat(self, request, context):
        """Reads (chat_guid is path-hostile, so these are :customVerb GETs with
        query parameters rather than resource paths).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChatCount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HasBackground(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeChatEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateChat': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateChat,
                    request_deserializer=photon_dot_imessage_dot_v1_dot_chat__service__pb2.CreateChatRequest.FromString,
                    response_serializer=photon_dot_imessage_dot_v1_dot_chat__service__pb2.CreateChatResponse.SerializeToString,
            ),
            'MarkChatRead': grpc.unary_unary_rpc_method_handler(
                    servicer.MarkChatRead,
                    request_deserializer=photon_dot_imessage_dot_v1_dot_chat__service__pb2.MarkChatReadRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SetBackground': grpc.unary_unary_rpc_method_handler(
                    servicer.SetBackground,
                    request_deserializer=photon_dot_imessage_dot_v1_dot_chat__service__pb2.SetBackgroundRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'RemoveBackground': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveBackground,
                    request_deserializer=photon_dot_imessage_dot_v1_dot_chat__service__pb2.RemoveBackgroundRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ShareContactInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.ShareContactInfo,
                    request_deserializer=photon_dot_imessage_dot_v1_dot_chat__service__pb2.ShareContactInfoRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SetTyping': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTyping,
                    request_deserializer=photon_dot_imessage_dot_v1_dot_chat__service__pb2.SetTypingRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetChat': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChat,
                    request_deserializer=photon_dot_imessage_dot_v1_dot_chat__service__pb2.GetChatRequest.FromString,
                    response_serializer=photon_dot_imessage_dot_v1_dot_chat__service__pb2.GetChatResponse.SerializeToString,
            ),
            'GetChatCount': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChatCount,
                    request_deserializer=photon_dot_imessage_dot_v1_dot_chat__service__pb2.GetChatCountRequest.FromString,
                    response_serializer=photon_dot_imessage_dot_v1_dot_chat__service__pb2.GetChatCountResponse.SerializeToString,
            ),
            'HasBackground': grpc.unary_unary_rpc_method_handler(
                    servicer.HasBackground,
                    request_deserializer=photon_dot_imessage_dot_v1_dot_chat__service__pb2.HasBackgroundRequest.FromString,
                    response_serializer=photon_dot_imessage_dot_v1_dot_chat__service__pb2.HasBackgroundResponse.SerializeToString,
            ),
            'SubscribeChatEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeChatEvents,
                    request_deserializer=photon_dot_imessage_dot_v1_dot_chat__service__pb2.SubscribeChatEventsRequest.FromString,
                    response_serializer=photon_dot_imessage_dot_v1_dot_chat__service__pb2.SubscribeChatEventsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'photon.imessage.v1.ChatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('photon.imessage.v1.ChatService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChatService(object):
    """---------------------------------------------------------------------------
    Service
    ---------------------------------------------------------------------------

    Chat-level reads, mutations, and event streams.
    """

    @staticmethod
    def CreateChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/photon.imessage.v1.ChatService/CreateChat',
            photon_dot_imessage_dot_v1_dot_chat__service__pb2.CreateChatRequest.SerializeToString,
            photon_dot_imessage_dot_v1_dot_chat__service__pb2.CreateChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MarkChatRead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/photon.imessage.v1.ChatService/MarkChatRead',
            photon_dot_imessage_dot_v1_dot_chat__service__pb2.MarkChatReadRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetBackground(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/photon.imessage.v1.ChatService/SetBackground',
            photon_dot_imessage_dot_v1_dot_chat__service__pb2.SetBackgroundRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveBackground(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/photon.imessage.v1.ChatService/RemoveBackground',
            photon_dot_imessage_dot_v1_dot_chat__service__pb2.RemoveBackgroundRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShareContactInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/photon.imessage.v1.ChatService/ShareContactInfo',
            photon_dot_imessage_dot_v1_dot_chat__service__pb2.ShareContactInfoRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetTyping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/photon.imessage.v1.ChatService/SetTyping',
            photon_dot_imessage_dot_v1_dot_chat__service__pb2.SetTypingRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/photon.imessage.v1.ChatService/GetChat',
            photon_dot_imessage_dot_v1_dot_chat__service__pb2.GetChatRequest.SerializeToString,
            photon_dot_imessage_dot_v1_dot_chat__service__pb2.GetChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChatCount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/photon.imessage.v1.ChatService/GetChatCount',
            photon_dot_imessage_dot_v1_dot_chat__service__pb2.GetChatCountRequest.SerializeToString,
            photon_dot_imessage_dot_v1_dot_chat__service__pb2.GetChatCountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HasBackground(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/photon.imessage.v1.ChatService/HasBackground',
            photon_dot_imessage_dot_v1_dot_chat__service__pb2.HasBackgroundRequest.SerializeToString,
            photon_dot_imessage_dot_v1_dot_chat__service__pb2.HasBackgroundResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeChatEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/photon.imessage.v1.ChatService/SubscribeChatEvents',
            photon_dot_imessage_dot_v1_dot_chat__service__pb2.SubscribeChatEventsRequest.SerializeToString,
            photon_dot_imessage_dot_v1_dot_chat__service__pb2.SubscribeChatEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
