# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: photon/imessage/v1/event_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'photon/imessage/v1/event_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ufo_ext_imessage.proto.photon.imessage.v1 import chat_types_pb2 as photon_dot_imessage_dot_v1_dot_chat__types__pb2
from ufo_ext_imessage.proto.photon.imessage.v1 import group_types_pb2 as photon_dot_imessage_dot_v1_dot_group__types__pb2
from ufo_ext_imessage.proto.photon.imessage.v1 import message_types_pb2 as photon_dot_imessage_dot_v1_dot_message__types__pb2
from ufo_ext_imessage.proto.photon.imessage.v1 import poll_types_pb2 as photon_dot_imessage_dot_v1_dot_poll__types__pb2
from ufo_ext_imessage.proto.photon.imessage.v1 import streaming_pb2 as photon_dot_imessage_dot_v1_dot_streaming__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&photon/imessage/v1/event_service.proto\x12\x12photon.imessage.v1\x1a#photon/imessage/v1/chat_types.proto\x1a$photon/imessage/v1/group_types.proto\x1a&photon/imessage/v1/message_types.proto\x1a#photon/imessage/v1/poll_types.proto\x1a\"photon/imessage/v1/streaming.proto\"F\n\x14\x43\x61tchUpEventsRequest\x12\x1b\n\x0e\x61\x66ter_sequence\x18\x01 \x01(\x04H\x00\x88\x01\x01\x42\x11\n\x0f_after_sequence\".\n\x15\x43\x61tchUpEventsComplete\x12\x15\n\rhead_sequence\x18\x01 \x01(\x04\"\xb5\x03\n\x15\x43\x61tchUpEventsResponse\x12\x15\n\x08sequence\x18\x01 \x01(\x04H\x01\x88\x01\x01\x12\x41\n\x0fmessage_changed\x18\n \x01(\x0b\x32&.photon.imessage.v1.MessageChangeEventH\x00\x12=\n\rgroup_changed\x18\x0b \x01(\x0b\x32$.photon.imessage.v1.GroupChangeEventH\x00\x12;\n\x0cpoll_changed\x18\x0c \x01(\x0b\x32#.photon.imessage.v1.PollChangeEventH\x00\x12;\n\x0c\x63hat_changed\x18\r \x01(\x0b\x32#.photon.imessage.v1.ChatChangeEventH\x00\x12=\n\x08\x63omplete\x18\x14 \x01(\x0b\x32).photon.imessage.v1.CatchUpEventsCompleteH\x00\x12\x32\n\theartbeat\x18\x63 \x01(\x0b\x32\x1d.photon.imessage.v1.HeartbeatH\x00\x42\t\n\x07payloadB\x0b\n\t_sequence2v\n\x0c\x45ventService\x12\x66\n\rCatchUpEvents\x12(.photon.imessage.v1.CatchUpEventsRequest\x1a).photon.imessage.v1.CatchUpEventsResponse0\x01\x42\t\xba\x02\x06PIMsg_b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'photon.imessage.v1.event_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\272\002\006PIMsg_'
  _globals['_CATCHUPEVENTSREQUEST']._serialized_start=250
  _globals['_CATCHUPEVENTSREQUEST']._serialized_end=320
  _globals['_CATCHUPEVENTSCOMPLETE']._serialized_start=322
  _globals['_CATCHUPEVENTSCOMPLETE']._serialized_end=368
  _globals['_CATCHUPEVENTSRESPONSE']._serialized_start=371
  _globals['_CATCHUPEVENTSRESPONSE']._serialized_end=808
  _globals['_EVENTSERVICE']._serialized_start=810
  _globals['_EVENTSERVICE']._serialized_end=928
# @@protoc_insertion_point(module_scope)
