# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: photon/imessage/v1/group_types.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'photon/imessage/v1/group_types.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from ufo_ext_imessage.proto.photon.imessage.v1 import address_types_pb2 as photon_dot_imessage_dot_v1_dot_address__types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$photon/imessage/v1/group_types.proto\x12\x12photon.imessage.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a&photon/imessage/v1/address_types.proto\"/\n\x17GroupDisplayNameChanged\x12\x14\n\x0c\x64isplay_name\x18\x01 \x01(\t\"Z\n\x15GroupParticipantAdded\x12\x41\n\x0bparticipant\x18\x01 \x01(\x0b\x32,.photon.imessage.v1.SingleServiceAddressInfo\"\\\n\x17GroupParticipantRemoved\x12\x41\n\x0bparticipant\x18\x01 \x01(\x0b\x32,.photon.imessage.v1.SingleServiceAddressInfo\"Y\n\x14GroupParticipantLeft\x12\x41\n\x0bparticipant\x18\x01 \x01(\x0b\x32,.photon.imessage.v1.SingleServiceAddressInfo\"\x12\n\x10GroupIconChanged\"\x12\n\x10GroupIconRemoved\"\xe3\x04\n\x10GroupChangeEvent\x12\x11\n\tchat_guid\x18\x01 \x01(\t\x12/\n\x0boccurred_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12@\n\x05\x61\x63tor\x18\x03 \x01(\x0b\x32,.photon.imessage.v1.SingleServiceAddressInfoH\x01\x88\x01\x01\x12\x12\n\nis_from_me\x18\x04 \x01(\x08\x12K\n\x14\x64isplay_name_changed\x18\n \x01(\x0b\x32+.photon.imessage.v1.GroupDisplayNameChangedH\x00\x12\x46\n\x11participant_added\x18\x0b \x01(\x0b\x32).photon.imessage.v1.GroupParticipantAddedH\x00\x12J\n\x13participant_removed\x18\x0c \x01(\x0b\x32+.photon.imessage.v1.GroupParticipantRemovedH\x00\x12\x44\n\x10participant_left\x18\r \x01(\x0b\x32(.photon.imessage.v1.GroupParticipantLeftH\x00\x12<\n\x0cicon_changed\x18\x0e \x01(\x0b\x32$.photon.imessage.v1.GroupIconChangedH\x00\x12<\n\x0cicon_removed\x18\x0f \x01(\x0b\x32$.photon.imessage.v1.GroupIconRemovedH\x00\x42\x08\n\x06\x63hangeB\x08\n\x06_actorB\t\xba\x02\x06PIMsg_b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'photon.imessage.v1.group_types_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\272\002\006PIMsg_'
  _globals['_GROUPDISPLAYNAMECHANGED']._serialized_start=133
  _globals['_GROUPDISPLAYNAMECHANGED']._serialized_end=180
  _globals['_GROUPPARTICIPANTADDED']._serialized_start=182
  _globals['_GROUPPARTICIPANTADDED']._serialized_end=272
  _globals['_GROUPPARTICIPANTREMOVED']._serialized_start=274
  _globals['_GROUPPARTICIPANTREMOVED']._serialized_end=366
  _globals['_GROUPPARTICIPANTLEFT']._serialized_start=368
  _globals['_GROUPPARTICIPANTLEFT']._serialized_end=457
  _globals['_GROUPICONCHANGED']._serialized_start=459
  _globals['_GROUPICONCHANGED']._serialized_end=477
  _globals['_GROUPICONREMOVED']._serialized_start=479
  _globals['_GROUPICONREMOVED']._serialized_end=497
  _globals['_GROUPCHANGEEVENT']._serialized_start=500
  _globals['_GROUPCHANGEEVENT']._serialized_end=1111
# @@protoc_insertion_point(module_scope)
