# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: photon/imessage/v1/poll_types.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'photon/imessage/v1/poll_types.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from ufo_ext_imessage.proto.photon.imessage.v1 import address_types_pb2 as photon_dot_imessage_dot_v1_dot_address__types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#photon/imessage/v1/poll_types.proto\x12\x12photon.imessage.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a&photon/imessage/v1/address_types.proto\"e\n\nPollOption\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x19\n\x11option_identifier\x18\x02 \x01(\t\x12\x1b\n\x0e\x63reator_handle\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\x11\n\x0f_creator_handle\"s\n\x13PollParticipantVote\x12\x41\n\x0bparticipant\x18\x01 \x01(\x0b\x32,.photon.imessage.v1.SingleServiceAddressInfo\x12\x19\n\x11option_identifier\x18\x02 \x01(\t\"\xb0\x01\n\x08PollInfo\x12\x19\n\x11poll_message_guid\x18\x01 \x01(\t\x12\x11\n\tchat_guid\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12/\n\x07options\x18\x04 \x03(\x0b\x32\x1e.photon.imessage.v1.PollOption\x12\x36\n\x05votes\x18\x05 \x03(\x0b\x32\'.photon.imessage.v1.PollParticipantVote\"M\n\x0bPollCreated\x12\r\n\x05title\x18\x01 \x01(\t\x12/\n\x07options\x18\x02 \x03(\x0b\x32\x1e.photon.imessage.v1.PollOption\"Q\n\x0fPollOptionAdded\x12\r\n\x05title\x18\x01 \x01(\t\x12/\n\x07options\x18\x02 \x03(\x0b\x32\x1e.photon.imessage.v1.PollOption\"&\n\tPollVoted\x12\x19\n\x11option_identifier\x18\x01 \x01(\t\"(\n\x0bPollUnvoted\x12\x19\n\x11option_identifier\x18\x01 \x01(\t\"\xaf\x03\n\x0fPollChangeEvent\x12\x11\n\tchat_guid\x18\x01 \x01(\t\x12\x19\n\x11poll_message_guid\x18\x02 \x01(\t\x12/\n\x0boccurred_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12@\n\x05\x61\x63tor\x18\x04 \x01(\x0b\x32,.photon.imessage.v1.SingleServiceAddressInfoH\x01\x88\x01\x01\x12\x12\n\nis_from_me\x18\x05 \x01(\x08\x12\x32\n\x07\x63reated\x18\n \x01(\x0b\x32\x1f.photon.imessage.v1.PollCreatedH\x00\x12;\n\x0coption_added\x18\x0b \x01(\x0b\x32#.photon.imessage.v1.PollOptionAddedH\x00\x12.\n\x05voted\x18\x0c \x01(\x0b\x32\x1d.photon.imessage.v1.PollVotedH\x00\x12\x32\n\x07unvoted\x18\r \x01(\x0b\x32\x1f.photon.imessage.v1.PollUnvotedH\x00\x42\x08\n\x06\x63hangeB\x08\n\x06_actorB\t\xba\x02\x06PIMsg_b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'photon.imessage.v1.poll_types_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\272\002\006PIMsg_'
  _globals['_POLLOPTION']._serialized_start=132
  _globals['_POLLOPTION']._serialized_end=233
  _globals['_POLLPARTICIPANTVOTE']._serialized_start=235
  _globals['_POLLPARTICIPANTVOTE']._serialized_end=350
  _globals['_POLLINFO']._serialized_start=353
  _globals['_POLLINFO']._serialized_end=529
  _globals['_POLLCREATED']._serialized_start=531
  _globals['_POLLCREATED']._serialized_end=608
  _globals['_POLLOPTIONADDED']._serialized_start=610
  _globals['_POLLOPTIONADDED']._serialized_end=691
  _globals['_POLLVOTED']._serialized_start=693
  _globals['_POLLVOTED']._serialized_end=731
  _globals['_POLLUNVOTED']._serialized_start=733
  _globals['_POLLUNVOTED']._serialized_end=773
  _globals['_POLLCHANGEEVENT']._serialized_start=776
  _globals['_POLLCHANGEEVENT']._serialized_end=1207
# @@protoc_insertion_point(module_scope)
