apiVersion: v1
kind: Service
metadata:
  name: ufo-serve
  labels:
    {{- include "ufo-tenant.labels" . | nindent 4 }}
spec:
  selector:
    app: ufo-serve
  ports:
    - name: http
      port: {{ .Values.serve_port }}
      targetPort: http
