apiVersion: v1
kind: ResourceQuota
metadata:
  name: selfhost-tenant
  labels:
    {{- include "selfhost-tenant.labels" . | nindent 4 }}
spec:
  hard:
    requests.cpu: {{ .Values.quota.requestsCpu | quote }}
    requests.memory: {{ .Values.quota.requestsMemory | quote }}
    requests.storage: {{ .Values.quota.requestsStorage | quote }}
    pods: {{ .Values.quota.pods | quote }}
---
apiVersion: v1
kind: LimitRange
metadata:
  name: selfhost-tenant
  labels:
    {{- include "selfhost-tenant.labels" . | nindent 4 }}
spec:
  limits:
    - type: Container
      default:
        cpu: {{ .Values.limitRange.default.cpu | quote }}
        memory: {{ .Values.limitRange.default.memory | quote }}
      defaultRequest:
        cpu: {{ .Values.limitRange.defaultRequest.cpu | quote }}
        memory: {{ .Values.limitRange.defaultRequest.memory | quote }}
