// Generated by `uv run python -m ufo_testsupport.contract` from core's pydantic models. Do not edit.

export type ActivityEvent = {
  kind: "activity" | "note";
  text: string;
};

export type AskQuestion = {
  question: string;
  options?: QuestionOption[] | null;
  multi_select?: boolean | null;
  free_text_only?: boolean | null;
  header?: string | null;
  allow_attachments?: boolean | null;
  chosen?: string | null;
};

export type AskUserInput = {
  title: string;
  questions: AskQuestion[];
  icon?: string | null;
};

export type CommentStep = {
  kind: "comment";
  id: string;
  text: string;
};

export type ConnectRequest = {
  provider: string;
  requester_member_id: string;
  shared?: boolean;
  grantee_agent_id?: string | null;
};

export type CredentialPrompt = {
  slot: string;
  prompt: string;
};

export type CredentialRequest = {
  reason: string;
  prompts: CredentialPrompt[];
  sealed: string;
};

export type DrainStep = {
  kind: "drain";
  arrivals: string[];
};

export type ExportStatus = {
  id: string;
  status: "queued" | "preparing" | "ready" | "failed" | "expired";
  created_at: string;
  finished_at: string | null;
  expires_at: string | null;
  size_bytes: number | null;
  error: string | null;
};

export type ExportView = {
  export: ExportStatus | null;
};

export type LostEnd = {
  kind: "lost";
};

export type Meter = {
  tokens: number;
  cost_micro_usd: number;
};

export type ObjectRef = {
  kind: string;
  name: string;
  agent?: string | null;
};

export type ParkedEnd = {
  kind: "parked";
  message: string;
};

export type QuestionOption = {
  label: string;
  description?: string | null;
};

export type ReplyStep = {
  kind: "reply";
  id: string;
  text: string;
};

export type ResumedStep = {
  kind: "resumed";
  attempt: string;
};

export type SourceRef = {
  kind: "web" | "workspace";
  title: string;
  url?: string;
  ref?: string;
  provider?: string;
};

export type SubagentRun = {
  profile: string;
  name?: string;
  conversation_id: string;
  events: ActivityEvent[];
  output: string;
  subagents: SubagentRun[];
  running: boolean;
  turn_id?: string | null;
  parent_turn_id?: string | null;
  current?: string | null;
};

export type TerminalEnd = {
  kind: "terminal";
  frame: TerminalFrame;
  at: string;
};

export type TerminalFrame = {
  status: "done" | "failed" | "cancelled";
  text?: string;
  incomplete_reason?: "round_budget" | null;
  error_class?: string | null;
  error_message?: string | null;
  tokens?: number;
  cost_micro_usd?: number;
  cache_percent?: number;
  model?: string;
  reasoning?: "auto" | "off" | "low" | "medium" | "high" | null;
  environment?: string | null;
  question?: AskUserInput | null;
  credential_request?: CredentialRequest | null;
  connect_request?: ConnectRequest | null;
  created?: ObjectRef[];
};

export type TextStep = {
  kind: "text";
  text: string;
  open: boolean;
};

export type ToolStep = {
  kind: "tool";
  label: string | null;
  call_id: string;
  sources: SourceRef[];
  open: boolean;
};

export type TurnRecord = {
  id: string | null;
  steps: Step[];
  runs: SubagentRun[];
  meter: Meter | null;
  end: TurnEnd | null;
};

export type Step = CommentStep | DrainStep | ReplyStep | ResumedStep | TextStep | ToolStep;

export type TurnEnd = LostEnd | ParkedEnd | TerminalEnd;
